name: Build Unity Client

on:
  push:
    branches: [main]

jobs:
  build-webgl-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      
      - name: Determine tags
        id: determine-tags
        run: |
          if [[ ${{ github.event_name }} == 'release' ]]; then
            echo "tags=latest,${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "tags=latest" >> $GITHUB_ENV
          fi
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/client-${{ github.event.repository.name }}
          tags: ${{ env.tags }}
          
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/webgl-client.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}